### ISSUE TITLE
how to recover signed nonce at backend?

### ISSUE THREAD

**Issue by aman-jangu** [rmeissner/py-eth-sig-utils#10]
Hello, First of all I want to say thanks for providing this awesome repo. 
I am trying to implement metamask login backed in django and came across this repo but I am facing an issue.
I have signature which I got from front end.
but when I use -
`a = recover_typed_data(signature_to_v_r_s(signature), signer_address)`
error - 
`TypeError: cannot convert 'str' object to bytes
`
Thanks

**Comment by rmeissner** [comment]
To recover the `address` you need to provide the data and the signatures (currently you provide `signature` and the `signer_address`). 

An example for this can be found in the tests: https://github.com/rmeissner/py-eth-sig-utils/blob/9bc5a291c0b7a5b5a3031e8c7f36a5e4bc99d97b/py_eth_sig_utils/tests/test_sign_typed_data.py#L51
