### ISSUE TITLE
release v0.4.0

### ISSUE THREAD

**Issue by oberstet** [rmeissner/py-eth-sig-utils#7]
Could we perhaps publish a new release v0.4.0 to PyPI? Not sure how / when this is usually done or what's the effort.

We'd like to publish some Python stuff that has this package as a dependency and depend on >v0.3.0. would enable setuptools based installs (which doesn't support installing from a git branch as pip does) ..

**Comment by rmeissner** [comment]
Hey, totally missed this comment. I can do this (releases are currently created when needed)

**Comment by rmeissner** [comment]
I created a release, that should be all that is required. Let me know if this doesn't work, else it would be nice if you could close the issue ;)

**Comment by oberstet** [comment]
yes, it works! fixed. thanks alot=)
